// 各国语言缩写列表
export const LANGUAGES_SHORT_LIST = [
  { value: "en", label: "en 英文" },
  { value: "en_US", label: "en_US 英文 (美国)" },
  { value: "ar", label: "ar 阿拉伯文" },
  { value: "ar_AE", label: "ar_AE 阿拉伯文 (阿拉伯联合酋长国)" },
  { value: "ar_BH", label: "ar_BH 阿拉伯文 (巴林)" },
  { value: "ar_DZ", label: "ar_DZ 阿拉伯文 (阿尔及利亚)" },
  { value: "ar_EG", label: "ar_EG 阿拉伯文 (埃及)" },
  { value: "ar_IQ", label: "ar_IQ 阿拉伯文 (伊拉克)" },
  { value: "ar_JO", label: "ar_JO 阿拉伯文 (约旦)" },
  { value: "ar_KW", label: "ar_KW 阿拉伯文 (科威特)" },
  { value: "ar_LB", label: "ar_LB 阿拉伯文 (黎巴嫩)" },
  { value: "ar_LY", label: "ar_LY 阿拉伯文 (利比亚)" },
  { value: "ar_MA", label: "ar_MA 阿拉伯文 (摩洛哥)" },
  { value: "ar_OM", label: "ar_OM 阿拉伯文 (阿曼)" },
  { value: "ar_QA", label: "ar_QA 阿拉伯文 (卡塔尔)" },
  { value: "ar_SA", label: "ar_SA 阿拉伯文 (沙特阿拉伯)" },
  { value: "ar_SD", label: "ar_SD 阿拉伯文 (苏丹)" },
  { value: "ar_SY", label: "ar_SY 阿拉伯文 (叙利亚)" },
  { value: "ar_TN", label: "ar_TN 阿拉伯文 (突尼斯)" },
  { value: "ar_YE", label: "ar_YE 阿拉伯文 (也门)" },
  { value: "be", label: "be 白俄罗斯文" },
  { value: "be_BY", label: "be_BY 白俄罗斯文 (白俄罗斯)" },
  { value: "bg", label: "bg 保加利亚文" },
  { value: "bg_BG", label: "bg_BG 保加利亚文 (保加利亚)" },
  { value: "ca", label: "ca 加泰罗尼亚文" },
  { value: "ca_ES", label: "ca_ES 加泰罗尼亚文 (西班牙)" },
  { value: "ca_ES_EURO", label: "ca_ES_EURO 加泰罗尼亚文 (西班牙,Euro)" },
  { value: "cs", label: "cs 捷克文" },
  { value: "cs_CZ", label: "cs_CZ 捷克文 (捷克共和国)" },
  { value: "da", label: "da 丹麦文" },
  { value: "da_DK", label: "da_DK 丹麦文 (丹麦)" },
  { value: "de", label: "de 德文" },
  { value: "de_AT", label: "de_AT 德文 (奥地利)" },
  { value: "de_AT_EURO", label: "de_AT_EURO 德文 (奥地利,Euro)" },
  { value: "de_CH", label: "de_CH 德文 (瑞士)" },
  { value: "de_DE", label: "de_DE 德文 (德国)" },
  { value: "de_DE_EURO", label: "de_DE_EURO 德文 (德国,Euro)" },
  { value: "de_LU", label: "de_LU 德文 (卢森堡)" },
  { value: "de_LU_EURO", label: "de_LU_EURO 德文 (卢森堡,Euro)" },
  { value: "el", label: "el 希腊文" },
  { value: "el_GR", label: "el_GR 希腊文 (希腊)" },
  { value: "en_AU", label: "en_AU 英文 (澳大利亚)" },
  { value: "en_CA", label: "en_CA 英文 (加拿大)" },
  { value: "en_GB", label: "en_GB 英文 (英国)" },
  { value: "en_IE", label: "en_IE 英文 (爱尔兰)" },
  { value: "en_IE_EURO", label: "en_IE_EURO 英文 (爱尔兰,Euro)" },
  { value: "en_NZ", label: "en_NZ 英文 (新西兰)" },
  { value: "en_ZA", label: "en_ZA 英文 (南非)" },
  { value: "es", label: "es 西班牙文" },
  { value: "es_BO", label: "es_BO 西班牙文 (玻利维亚)" },
  { value: "es_AR", label: "es_AR 西班牙文 (阿根廷)" },
  { value: "es_CL", label: "es_CL 西班牙文 (智利)" },
  { value: "es_CO", label: "es_CO 西班牙文 (哥伦比亚)" },
  { value: "es_CR", label: "es_CR 西班牙文 (哥斯达黎加)" },
  { value: "es_DO", label: "es_DO 西班牙文 (多米尼加共和国)" },
  { value: "es_EC", label: "es_EC 西班牙文 (厄瓜多尔)" },
  { value: "es_ES", label: "es_ES 西班牙文 (西班牙)" },
  { value: "es_ES_EURO", label: "es_ES_EURO 西班牙文 (西班牙,Euro)" },
  { value: "es_GT", label: "es_GT 西班牙文 (危地马拉)" },
  { value: "es_HN", label: "es_HN 西班牙文 (洪都拉斯)" },
  { value: "es_MX", label: "es_MX 西班牙文 (墨西哥)" },
  { value: "es_NI", label: "es_NI 西班牙文 (尼加拉瓜)" },
  { value: "et", label: "et 爱沙尼亚文" },
  { value: "es_PA", label: "es_PA 西班牙文 (巴拿马)" },
  { value: "es_PE", label: "es_PE 西班牙文 (秘鲁)" },
  { value: "es_PR", label: "es_PR 西班牙文 (波多黎哥)" },
  { value: "es_PY", label: "es_PY 西班牙文 (巴拉圭)" },
  { value: "es_SV", label: "es_SV 西班牙文 (萨尔瓦多)" },
  { value: "es_UY", label: "es_UY 西班牙文 (乌拉圭)" },
  { value: "es_VE", label: "es_VE 西班牙文 (委内瑞拉)" },
  { value: "et_EE", label: "et_EE 爱沙尼亚文 (爱沙尼亚)" },
  { value: "fi", label: "fi 芬兰文" },
  { value: "fi_FI", label: "fi_FI 芬兰文 (芬兰)" },
  { value: "fi_FI_EURO", label: "fi_FI_EURO 芬兰文 (芬兰,Euro)" },
  { value: "fr", label: "fr 法文" },
  { value: "fr_BE", label: "fr_BE 法文 (比利时)" },
  { value: "fr_BE_EURO", label: "fr_BE_EURO 法文 (比利时,Euro)" },
  { value: "fr_CA", label: "fr_CA 法文 (加拿大)" },
  { value: "fr_CH", label: "fr_CH 法文 (瑞士)" },
  { value: "fr_FR", label: "fr_FR 法文 (法国)" },
  { value: "fr_FR_EURO", label: "fr_FR_EURO 法文 (法国,Euro)" },
  { value: "fr_LU", label: "fr_LU 法文 (卢森堡)" },
  { value: "fr_LU_EURO", label: "fr_LU_EURO 法文 (卢森堡,Euro)" },
  { value: "hr", label: "hr 克罗地亚文" },
  { value: "hr_HR", label: "hr_HR 克罗地亚文 (克罗地亚)" },
  { value: "hu", label: "hu 匈牙利文" },
  { value: "hu_HU", label: "hu_HU 匈牙利文 (匈牙利)" },
  { value: "is", label: "is 冰岛文" },
  { value: "is_IS", label: "is_IS 冰岛文 (冰岛)" },
  { value: "it", label: "it 意大利文" },
  { value: "it_CH", label: "it_CH 意大利文 (瑞士)" },
  { value: "it_IT", label: "it_IT 意大利文 (意大利)" },
  { value: "it_IT_EURO", label: "it_IT_EURO 意大利文 (意大利,Euro)" },
  { value: "iw", label: "iw 希伯来文" },
  { value: "iw_IL", label: "iw_IL 希伯来文 (以色列)" },
  { value: "ja", label: "ja 日文" },
  { value: "ja_JP", label: "ja_JP 日文 (日本)" },
  { value: "ko", label: "ko 朝鲜文" },
  { value: "ko_KR", label: "ko_KR 朝鲜文 (南朝鲜)" },
  { value: "lt", label: "lt 立陶宛文" },
  { value: "lt_LT", label: "lt_LT lt_LT 立陶宛文 (立陶宛)" },
  { value: "lv", label: "lv 拉托维亚文(列托)" },
  { value: "lv_LV", label: "lv_LV 拉托维亚文(列托) (拉脱维亚)" },
  { value: "mk", label: "mk 马其顿文" },
  { value: "mk_MK", label: "mk_MK 马其顿文 (马其顿王国)" },
  { value: "nl", label: "nl 荷兰文" },
  { value: "nl_BE", label: "nl_BE 荷兰文 (比利时)" },
  { value: "nl_BE_EURO", label: "nl_BE_EURO 荷兰文 (比利时,Euro)" },
  { value: "nl_NL", label: "nl_NL 荷兰文 (荷兰)" },
  { value: "nl_NL_EURO", label: "nl_NL_EURO 荷兰文 (荷兰,Euro)" },
  { value: "no", label: "no 挪威文" },
  { value: "no_NO", label: "no_NO 挪威文 (挪威)" },
  { value: "no_NO_NY", label: "no_NO_NY 挪威文 (挪威,Nynorsk)" },
  { value: "pl", label: "pl 波兰文" },
  { value: "pl_PL", label: "pl_PL 波兰文 (波兰)" },
  { value: "pt", label: "pt 葡萄牙文" },
  { value: "pt_BR", label: "pt_BR 葡萄牙文 (巴西)" },
  { value: "pt_PT", label: "pt_PT 葡萄牙文 (葡萄牙)" },
  { value: "pt_PT_EURO", label: "pt_PT_EURO 葡萄牙文 (葡萄牙,Euro)" },
  { value: "ro", label: "ro 罗马尼亚文" },
  { value: "ro_RO", label: "ro_RO 罗马尼亚文 (罗马尼亚)" },
  { value: "ru", label: "ru 俄文" },
  { value: "ru_RU", label: "ru_RU 俄文 (俄罗斯)" },
  { value: "sh", label: "sh 塞波尼斯-克罗地亚文" },
  { value: "sh_YU", label: "sh_YU 塞波尼斯-克罗地亚文 (南斯拉夫)" },
  { value: "sk", label: "sk 斯洛伐克文" },
  { value: "sk_SK", label: "sk_SK 斯洛伐克文 (斯洛伐克)" },
  { value: "sl", label: "sl 斯洛文尼亚文" },
  { value: "sl_SI", label: "sl_SI 斯洛文尼亚文 (斯洛文尼亚)" },
  { value: "sq", label: "sq 阿尔巴尼亚文" },
  { value: "sq_AL", label: "sq_AL 阿尔巴尼亚文 (阿尔巴尼亚)" },
  { value: "sr", label: "sr 塞尔维亚文" },
  { value: "sr_YU", label: "sr_YU 塞尔维亚文 (南斯拉夫)" },
  { value: "sv", label: "sv 瑞典文" },
  { value: "sv_SE", label: "sv_SE 瑞典文 (瑞典)" },
  { value: "th", label: "th 泰文" },
  { value: "th_TH", label: "th_TH 泰文 (泰国)" },
  { value: "tr", label: "tr 土耳其文" },
  { value: "tr_TR", label: "tr_TR 土耳其文 (土耳其)" },
  { value: "uk", label: "uk 乌克兰文" },
  { value: "uk_UA", label: "uk_UA 乌克兰文 (乌克兰)" },
  { value: "zh", label: "zh 中文" },
  { value: "zh_CN", label: "zh_CN 中文 (中国)" },
  { value: "zh_HK", label: "zh_HK 中文 (香港)" },
  { value: "zh_TW", label: "zh_TW 中文 (台湾)" }
];
