import { shallow } from 'enzyme';
import Chart from '../index.js';
import i18n from 'utils/i18n';

const activeTypes = [
  {
    key: 'NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE',
    name: i18n['dashboard.data_type.NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE']
  },
  {
    key: 'NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE',
    name: i18n['dashboard.data_type.NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE']
  }
];

const labels = [
  '2017-11-08',
  '2017-11-09',
  '2017-11-10',
  '2017-11-11',
  '2017-11-12',
  '2017-11-13',
  '2017-11-14',
  '2017-11-15',
  '2017-11-16',
  '2017-11-17',
  '2017-11-18',
  '2017-11-19',
  '2017-11-20',
  '2017-11-21',
  '2017-11-22',
  '2017-11-23',
  '2017-11-24',
  '2017-11-25',
  '2017-11-26',
  '2017-11-27',
  '2017-11-28',
  '2017-11-29',
  '2017-11-30',
  '2017-12-01',
  '2017-12-02',
  '2017-12-03',
  '2017-12-04',
  '2017-12-05',
  '2017-12-06',
  '2017-12-07'
];
const data = [
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 8,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 22,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 4,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 1,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 6,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 12,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 17,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 11,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 19,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 2,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 4,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 8,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 10,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 15,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 12,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 29,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 4,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 6,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 21,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 35,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 22,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 16,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 1,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 7,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 10,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 12,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  },
  {
    NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
    NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
  }
];

describe('活跃用户 chart', () => {
  const wrap = shallow(
    <Chart tabs={activeTypes} data={data} labels={labels} />
  );
  it('正常显示', () => {
    expect(wrap.find('[data-test="container"]').exists()).toBe(true);
  });
  it('切换', () => {
    wrap
      .find('[data-test="nav-item"]')
      .at(1)
      .simulate('click');
    setTimeout(() => {
      expect(wrap.state('activeData')).toBe(
        'NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE'
      );
    });
  });
});
