const PRE_FIX = 'CUSTOMER_MANAGEMENT_';

const ActionTypes = {
    TOGGLE_CUSTOMER: `${PRE_FIX}TOGGLE_CUSTOMER`,
    TOGGLE_ALL_CUSTOMER: `${PRE_FIX}TOGGLE_ALL_CUSTOMER`,

    FETCH_CUSTOMERS: `${PRE_FIX}FETCH_CUSTOMERS`,
    DELETE_CUSTOMER: `${PRE_FIX}DELETE_CUSTOMER`,
    MODIFY_CUSTOMER: `${PRE_FIX}MODIFY_CUSTOMER`,
    ADD_CUSTOMER: `${PRE_FIX}ADD_CUSTOMER`,
    ADD_CONTACT: `${PRE_FIX}ADD_CONTACT`, //增加联系人
    ADD_SALES_RECORD: `${PRE_FIX}ADD_SALES_RECORD`,

    MARK_IMPORTANCE: `${PRE_FIX}MARK_IMPORTANCE`, //标记重要
    MARK_PRIORITY: `${PRE_FIX}MARK_PRIORITY`, //标记紧急

    SWITCH_OWE: `${PRE_FIX}SWITCH_OWE`,//划分归属                                                                                 .314
    FETCH_CUSTOMER_RECYCLEBIN_ITEMS: `${PRE_FIX}FETCH_CUSTOMER_RECYCLEBIN_ITEMS`,
    RESTORE_CUSTOMER_RECYCLEBIN_ITEM: `${PRE_FIX}RESTORE_CUSTOMER_RECYCLEBIN_ITEM`,
    CLEAR_CUSTOMER_RECYCLEBIN_ITEM: `${PRE_FIX}CLEAR_CUSTOMER_RECYCLEBIN_ITEM`,

    TOGGLE_SALESTARGET: `${PRE_FIX}TOGGLE_SALESTARGET`,
    TOGGLE_ALL_SALESTARGET: `${PRE_FIX}TOGGLE_ALL_SALESTARGET`,

    FETCH_SALESTARGET: `${PRE_FIX}FETCH_SALESTARGET`,//追踪销售目标
    ADD_SALESTARGET: `${PRE_FIX}ADD_SALESTARGET`,//添加销售目标
    FETCH_USERS_SALESTARGET: `${PRE_FIX}FETCH_USERS_SALESTARGET`, // 添加销售目标中的用户列表
    RECEIVE_USERS_SALESTARGET: `${PRE_FIX}RECEIVE_USERS_SALESTARGET`, // 拉取添加销售目标中的用户列表成功
    MODIFY_SALESTARGET: `${PRE_FIX}MODIFY_SALESTARGET`,
    DELETE_SALESTARGET: `${PRE_FIX}DELETE_SALESTARGET`,//删除销售目标
    RECYLE_SALESTARGET: `${PRE_FIX}RECYLE_SALESTARGET`,//销售目标回收站
    CLEAR_SALESTARGETRECYLE: `${PRE_FIX}CLEAR_SALESTARGETRECYLE`,//清空销售目标回收站
    FETCH_USERS: `${PRE_FIX}FETCH_USERS`,

    SEAERCH_SALESREPORT: `${PRE_FIX}SEAERCH_SALESREPORT`,//查询销售报表
    FILTER_SALESREPORT: `${PRE_FIX}FILTER_SALESREPORT`,//筛选不同条件的报表

    TOGGLE_TABLE_ITEM: `${PRE_FIX}TOGGLE_TABLE_ITEM`,
    TOGGLE_TABLE_ALL_ITEMS: `${PRE_FIX}TOGGLE_TABLE_ALL_ITEMS`,

    FETCH_SALESCONTRACT: `${PRE_FIX}FETCH_SALESCONTRACT`,
    ADD_SALESCONTRACT: `${PRE_FIX}ADD_SALESCONTRACT`,
    MODIFY_SALESCONTRACT: `${PRE_FIX}MODIFY_SALESCONTRACT`,
    DELETE_SALESCONTRACT: `${PRE_FIX}DELETE_SALESCONTRACT`,
    SUBMIT_SALESCONTRACT: `${PRE_FIX}SUBMIT_SALESCONTRACT`, //提交审核合同

    FETCH_CONTACTS: `${PRE_FIX}FETCH_CONTACTS`,   //获取（或查询）联系人列表
    MARK_CONTACTS: `${PRE_FIX}MARK_CONTACTS`,     //标记联系人
    ADD_CONTACTS: `${PRE_FIX}ADD_CONTACTS`,       //添加联系人
    DELETE_CONTACTS: `${PRE_FIX}DELETE_CONTACTS`, //移除联系人
    FETCH_RECYCLEBIN_CONTACTS: `${PRE_FIX}FETCH_RECYCLEBIN_CONTACTS`,  //获取（或查询）回收站联系人列表
    CLEAR_RECYCLEBIN_CONTACTS: `${PRE_FIX}CLEAR_RECYCLEBIN_CONTACTS`,  //删除回收站联系人
    FETCH_SCALE: `${PRE_FIX}FETCH_SCALE`,//获取客户规模列表
    FETCH_CUSTOMER_SOURCE: `${PRE_FIX}FETCH_CUSTOMER_SOURCE`,//获取客户资源列表
    FETCH_CUSTOMER_TYPE: `${PRE_FIX}FETCH_CUSTOMER_TYPE` ,//获取客户类型列表
    FETCH_CUSTOMER_ZONE: `${PRE_FIX}FETCH_CUSTOMER_ZONE`,//获取客户地区
    FETCH_CUSTOMER_OWE: `${PRE_FIX}FETCH_CUSTOMER_OWE`,//获取客户归属
    FETCH_INDICATORS: `${PRE_FIX}FETCH_INDICATORS`, //获取考核指标
    RECEIVE_COMMUNICATION_SALSE_RECORD: `${PRE_FIX}RECEIVE_COMMUNICATION_SALSE_RECORD`, // 获取销售记录里面沟通方式

    // 获取自定义字段列表
    FETCH_CUSTOMER_FIELDS: `${PRE_FIX}FETCH_CUSTOMER_FIELDS`,
    FETCH_COUNTRY_CODE: `${PRE_FIX}FETCH_COUNTRY_CODE`,
};

export {ActionTypes}
