const ActionTypes = {
    ADD_PROJECT: 'ADD_PROJECT',
    ADD_CATEGORY: 'ADD_CATEGORY',
    ADD_STEPS: 'ADD_STEPS',
    LIST_PROJECTS: 'LIST_PROJECTS',

    TOGGLE_TABLE_ITEM: 'TOGGLE_TABLE_ITEM',
    TOGGLE_TABLE_ALL_ITEMS: 'TOGGLE_TABLE_ALL_ITEMS',

    LOAD_TODO_BOARD_DATA: 'LOAD_TODO_BOARD_DATA', //代办看板
    LOAD_INPROGRESS_BOARD_DATA: 'LOAD_INPROGRESS_BOARD_DATA', //处理中看板
    LOAD_DONE_BOARD_DATA: 'LOAD_DONE_BOARD_DATA', //已完成看板
    LOAD_CLOSED_BOARD_DATA: 'LOAD_CLOSED_BOARD_DATA', //已关闭看板

    LOAD_LIST_VIEW_DATA: 'LOAD_LIST_VIEW_DATA', //列表数据
    LOAD_RECYCLEBIN_DATA: 'LOAD_RECYCLEBIN_DATA', //回收站数据
    LOAD_TASK_IMPORTANCE_CATEGORIES: 'LOAD_TASK_IMPORTANCE_CATEGORIES', //任务重要性列表

    CLAIM_TASK: 'CLAIM_TASK', //认领任务
    REMOVE_TASK: 'REMOVE_TASK',
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    FETCH_LOGS: 'FETCH_LOGS',

    LOAD_PROJECT_CATEGORIES: 'LOAD_PROJECT_CATEGORIES',
    GET_STEP_DATA: 'GET_STEP_DATA' //获取任务步骤数据
}

export {ActionTypes}