import { connect } from 'react-redux';
import { submit, change, touch } from 'redux-form';
import TaskDetails from '../components/TaskDetails';
import { showTopAlert, showTipsModal, bindCtid } from 'commonActions/actions';
import {
  getDetails,
  approvalTask,
  getTaskMembers,
  getPriorityOptions,
  rejectTask,
  updateTaskBasicData,
  getAccountForm,
  getFormData,
  getAccountDropdownData,
  submitAccountForm,
  getExternalFormData,
  getLog,
  getApprovalProcess,
  addComment,
  clearData,
  getServerPasswordRegular,
  getSameAccount,
  getUserRole,
  getServerList,
  getPasswordStrength,
  getFormColumns,
  checkAccount,
  getWithdrawFormField,
  getCtraderCurrencyByServerId,
  getSettingInfo,
  validateAccountIdNum,
  checkRealState,
  checkEmailRepeat,
  haveTwUser,
  withdrawCustomType,
  getCurrentRate,
  getAccountInfo,
  getAccountInfoPosition,
  changeAccountForm
} from '../controls/TaskDetailsActions';

import {
  getTheTask,
  getTaskGroupTasks,
  refreshTasks,
  verifyIdentity
} from '../controls/actions';

export default connect(
  ({
    taskmgmt,
    taskmgmt: { taskDetails, objectDetails, searchParams, userAgentColumns },
    common: { userRights, userInfo, accountTypes, versionRights }
  }) => {
    return {
      data: taskDetails.details,
      priorityOptions: taskDetails.priorityOptions,
      taskMembers: taskDetails.taskMembers,
      objectDetails,
      formFields: taskDetails.formFields,
      showFormFields: taskDetails.showFormFields,
      formData: taskDetails.formData,
      accountDropdownData: taskDetails.accountDropdownData,
      log: taskDetails.log,
      passwordRegular: taskDetails.passwordRegular,
      approvalProcess: taskDetails.approvalProcess,
      userInfo: userInfo,
      sameAccounts: taskDetails.sameAccounts,
      searchParams: searchParams,
      userAgentColumns,
      roleList: taskDetails.roleList,
      serverList: taskDetails.serverList,
      formColumns: taskDetails.formColumns,
      passwordStrength: taskDetails.passwordStrength,
      taskType: taskmgmt.taskType,
      withdrawFormField: taskDetails.withdrawFormField,
      settingInfo: taskDetails.settingInfo,
      isAdaptOn: taskmgmt.isAdaptOn,
      userRights,
      withdrawTypes: taskDetails.withdrawTypes,
      accountTypes,
      versionRights,
      currentRate: taskDetails.currentRate,
      accountInfoPosition: taskDetails.accountInfoPosition,
      accountInfo: taskDetails.accountInfo
    };
  },
  {
    showTipsModal,
    showTopAlert,
    getDetails,
    getTheTask,
    rejectTask,
    approvalTask,
    getTaskMembers,
    getPriorityOptions,
    updateTaskBasicData,
    getTaskGroupTasks,
    getAccountForm,
    getFormData,
    submitForm: submit,
    getAccountDropdownData,
    submitAccountForm,
    getExternalFormData,
    getLog,
    getApprovalProcess,
    addComment,
    clearData,
    getServerPasswordRegular,
    getSameAccount,
    refreshTasks,
    getUserRole,
    getServerList,
    getPasswordStrength,
    getFormColumns,
    checkAccount,
    getWithdrawFormField,
    getCtraderCurrencyByServerId,
    changeFormField: change,
    touchFromField: touch,
    getSettingInfo,
    verifyIdentity,
    validateIdNum: validateAccountIdNum,
    bindCtid,
    checkRealState,
    checkEmailRepeat,
    haveTwUser,
    withdrawCustomType,
    getCurrentRate,
    getAccountInfo,
    getAccountInfoPosition,
    changeAccountForm
  }
)(TaskDetails);
