import { shallow } from 'enzyme';
import Root from '../index.js';

const trendData = {
  labels: [
    '2017-11-08',
    '2017-11-09',
    '2017-11-10',
    '2017-11-11',
    '2017-11-12',
    '2017-11-13',
    '2017-11-14',
    '2017-11-15',
    '2017-11-16',
    '2017-11-17',
    '2017-11-18',
    '2017-11-19',
    '2017-11-20',
    '2017-11-21',
    '2017-11-22',
    '2017-11-23',
    '2017-11-24',
    '2017-11-25',
    '2017-11-26',
    '2017-11-27',
    '2017-11-28',
    '2017-11-29',
    '2017-11-30',
    '2017-12-01',
    '2017-12-02',
    '2017-12-03',
    '2017-12-04',
    '2017-12-05',
    '2017-12-06',
    '2017-12-07'
  ],
  data: [
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 8,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 22,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 4,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 1,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 6,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 12,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 17,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 11,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 19,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 2,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 4,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 8,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 10,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 15,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 12,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 29,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 4,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 6,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 21,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 35,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 22,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 16,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 1,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 7,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 10,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 12,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    },
    {
      NEW_CUSTOMER_TENANT_ACTIVE_TW_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_CTRADER_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_DEAL_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT5_LOGIN_PAGE: 0,
      NEW_CUSTOMER_TENANT_ACTIVE_MT4_LOGIN_PAGE: 0
    }
  ]
};

function getTrendDatas() {
  return Promise.resolve(trendData);
}

const searchParams = {
  timeRange: 'DAY',
  fromTime: '2017-11-07T16:00:00.000Z',
  toTime: '2017-12-07T15:59:59.999Z',
  type: 'NEW_CUSTOMER_ACTIVE_PANEL'
};

const match = { url: '/dashboard/customer-data/active-customer' };
const paginationInfo = { pageSize: 50, total: 30, pageNo: 1 };
function fn() {}

describe('活跃用户 Root', () => {
  const wrap = shallow(
    <Root
      trendData={trendData}
      paginationInfo={paginationInfo}
      match={match}
      dashboardViewRight={{ checkCustomer: true }}
      searchParams={searchParams}
      modifyParams={fn}
      getTrendDatas={getTrendDatas}
      setDashboardViewRight={fn}
    />
  );
  it('正常显示', () => {
    expect(wrap.find('[data-test="container"]').exists()).toBe(true);
  });
});
