
const constants = {
    CUSTOMER_IMPORTANCE_HIGH: 'CUSTOMER_IMPORTANCE_HIGH',
    CUSTOMER_IMPORTANCE_NONE: 'CUSTOMER_IMPORTANCE_NONE',

    CUSTOMER_PRIORITY_HIGH: 'CUSTOMER_PRIORITY_HIGH',
    CUSTOMER_PRIORITY_NONE: 'CUSTOMER_PRIORITY_NONE',
}
export default constants;