const constants = {
    SALESTARGET_IMPORTANCE_HIGH: 'SALESTARGET_IMPORTANCE_HIGH',
    SALESTARGET_IMPORTANCE_NONE: 'SALESTARGET_IMPORTANCE_NONE',

    SALESTARGET_PRIORITY_HIGH: 'SALESTARGET_PRIORITY_HIGH',
    SALESTARGET_PRIORITY_NONE: 'SALESTARGET_PRIORITY_NONE',
}
export default constants;